/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn how to create Gradle builds at https://guides.gradle.org/creating-new-gradle-builds/
 */
plugins {
    application
}

application {
    mainClassName = "io.fobo66.crypto.Lab4"
}

allprojects {
    repositories {
        mavenCentral()
    }

    dependencies {
        implementation("org.apache.commons:commons-rng-core:1.1")
        implementation("org.apache.commons:commons-rng-simple:1.1")
        implementation("org.apache.commons:commons-rng-client-api:1.1")
        implementation("org.jetbrains:annotations:16.0.3")
        implementation("commons-cli:commons-cli:1.4")
    }
}